version: 2
python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
sphinx:
  builder: dirhtml
  configuration: docs/conf.py
formats:
  - pdf
  - epub
build:
  os: "ubuntu-24.04"
  tools:
    python: "3.13"
